apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: article-analysis
spec:
  enabled: true
  requires: ">=2.21.0"
  settingName: article-analysis-settings
  configMapName: article-analysis-configMap
  author:
    name: shirainbown
    website: https://git.ali.songshiyu.cn
  logo: ""
  displayName: 文章数据分析
  description: 类似 CSDN 的文章数据看板：阅读量、评论、点赞数据一览，支持搜索、筛选与排序。
  homepage: https://git.ali.songshiyu.cn/ssy/plugin-article-analysis
  repo: https://git.ali.songshiyu.cn/ssy/plugin-article-analysis
  issues: https://git.ali.songshiyu.cn/ssy/plugin-article-analysis/issues
  version: "@version@"
  license:
    - name: "MIT"
